- Using Scipy lecture notes: https://www.scipy-lectures.org/intro/numpy/index.html

In [35]:
import numpy as np

In [36]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

-----------------
- Following commands help us in searching NumPy documentation

In [32]:
np.array?

In [ ]:
np.lookfor('dimension number')

------------------
- Creating arrays, multidimensional

In [ ]:
b = np.array([[0, 2, 1], [3, 5, 4]])  # 2 x 3 matrix.

In [8]:
b

array([[0, 2, 1],
       [3, 5, 4]])

In [9]:
b.ndim

2

In [11]:
b.shape

(2, 3)

In [12]:
len(b) # returns the size of the first dimension

2

In [29]:
c = np.array([
    [
        [1, 2], 
        [2, 4]
    ], 
    [
        [3, 5], 
        [4, 3]
    ]
])   # 2 x 2 x 2 matrix.

In [27]:
c

array([[[1, 2],
        [2, 4]],

       [[3, 5],
        [4, 3]]])

In [28]:
c.shape

(2, 2, 2)

------------------------------
- Creating arrays using functions available in NumPy library.
Using `arange()` and `linspace()`

In [41]:
a = np.arange(10)  # 0 .. n-1 (!)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
b = np.arange(1, 12, 3)   # start, end (not included), step
b

array([ 1,  4,  7, 10])

In [43]:
c = np.linspace(0, 2, 6)   # start, end, num-points
c

array([0. , 0.4, 0.8, 1.2, 1.6, 2. ])

In [45]:
d = np.linspace(0, 1, 5, endpoint=False)   # don't include the last point in the list
d

array([0. , 0.2, 0.4, 0.6, 0.8])

In [46]:
a = np.ones((3, 3))   # 3 x 3 matrix of ones. the dimensions are passed as a tuple
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
b = np.zeros((2, 2))   # 2 x 2 matrix of zeros
b

array([[0., 0.],
       [0., 0.]])

In [49]:
c = np.eye(3)          # 3 x 3 identity matrix
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
d = np.diag(np.array([1, 2, 3, 4]))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Using np.random for creating arrays



In [57]:
a = np.random.rand(3, 2)     # uniform in [0, 1]
a

array([[0.75354372, 0.27058423],
       [0.52230328, 0.09832853],
       [0.71363667, 0.88404059]])

In [54]:
b = np.random.randn(4)    # Gaussian
b

array([-3.2771929 , -1.84856065,  0.67212494, -1.49297925])

In [58]:
np.random.randn?

In [6]:
list1 = ['a', 'b']
list2 = [i for i in range(4)]
# list2 = [0, 1, 2, 3]

test_zip = zip(list1, list2)
list(test_zip)

[('a', 0), ('b', 1)]